apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-v1
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - image: hashicorp/http-echo
          args:
            - "-text=version:v1"
            - -listen=:8080
          imagePullPolicy: Always
          name: echo-v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-v1
  namespace: echo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo-v2
  namespace: echo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: echo-v1
  namespace: echo 
spec:
  kube:
    selector:
      app: echo
    serviceName: echo-v1
    serviceNamespace: echo
    servicePort: 80
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: echo-v2
  namespace: echo
spec:
  kube:
    selector:
      app: echo
    serviceName: echo-v2
    serviceNamespace: echo
    servicePort: 80
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: echo-routes-a
  namespace: echo
  labels:
    test-label: label-1
    another-label: label-another
spec:
  routes:
    - matchers:
      - prefix: /a/b
      name: route-b
      routeAction:
        multi:
          destinations:
          - destination:
              upstream:
                name: echo-v1
                namespace: echo
            weight: 100
    - matchers:
      - prefix: /a/c
      name: route-c
      routeAction:
        multi:
          destinations:
          - destination:
              upstream:
                name: echo-v1
                namespace: echo
            weight: 100
          - destination:
              upstream:
                name: echo-v2
                namespace: echo
            weight: 0
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: echo-routes-b
  namespace: echo
  labels:
    test-label: label-1
    yet-another-label: label-another-yet
spec:
  routes:
    - matchers:
      - prefix: /b/b
      name: route-b
      routeAction:
        single:
          upstream:
            name: echo-v1
            namespace: echo
    - matchers:
      - prefix: /b/c
      name: route-c
      routeAction:
        multi:
          destinations:
          - destination:
              upstream:
                name: echo-v1
                namespace: echo
            weight: 100
          - destination:
              upstream:
                name: echo-v2
                namespace: echo
            weight: 0

---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: echo
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /a
      delegateAction:
        ref:
          name: echo-routes-a
          namespace: echo
    - matchers:
      - prefix: /b
      delegateAction:
        ref:
          name: echo-routes-b
          namespace: echo

